<?php

namespace todo\_generated;

/**
 * Generated by Codeception. Kept in the repository so the unit suite can run
 * in read-only module checkouts without a preceding build step.
 */
trait UnitTesterActions
{
}
